<?php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;

class FilmSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $films = [
            [
                'titre' => 'Tilaï',
                'duree_min' => 81,
                'annee' => 1990,
                'langue' => 'Mooré',
                'genre' => 'Drame',
                'synopsis' => 'De retour dans son village après une longue absence, Saga découvre que celle qui lui était promise a épousé son père.',
                'realisateur' => 'Idrissa Ouédraogo',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Grand Prix du Jury - Cannes 1990',
            ],
            [
                'titre' => 'Saaraba',
                'duree_min' => 90,
                'annee' => 1991,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'Un jeune homme revient dans son pays natal après des études en Europe, en quête d\'un idéal.',
                'realisateur' => 'Amadou Saalum Seck',
                'pays' => 'Sénégal',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Wênd Kûuni',
                'titre_original' => 'Le don de Dieu',
                'duree_min' => 75,
                'annee' => 1982,
                'langue' => 'Mooré',
                'genre' => 'Drame',
                'synopsis' => 'Un jeune garçon muet recueilli par une famille recouvre la parole après un drame.',
                'realisateur' => 'Gaston Kaboré',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Étalon de Yennenga 1983',
            ],
            [
                'titre' => 'Le Damier',
                'titre_original' => 'Papa National Oyé',
                'duree_min' => 90,
                'annee' => 1996,
                'langue' => 'Français',
                'genre' => 'Comédie dramatique',
                'synopsis' => 'Une satire du pouvoir africain à travers une partie de jeu de dames.',
                'realisateur' => 'Dani Kouyaté',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Yaaba',
                'duree_min' => 90,
                'annee' => 1989,
                'langue' => 'Mooré',
                'genre' => 'Drame',
                'synopsis' => 'Deux enfants se lient d\'amitié avec une vieille femme rejetée par son village.',
                'realisateur' => 'Idrissa Ouédraogo',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Prix de la Critique Internationale - Cannes 1989',
            ],
            [
                'titre' => 'Keïta ! L\'héritage du griot',
                'duree_min' => 94,
                'annee' => 1995,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'Un griot initie un jeune garçon à la légende de Soundiata Keïta.',
                'realisateur' => 'Dani Kouyaté',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Étalon de Yennenga 1997',
            ],
            [
                'titre' => 'Sarraounia',
                'duree_min' => 122,
                'annee' => 1986,
                'langue' => 'Français',
                'genre' => 'Historique',
                'synopsis' => 'La résistance d\'une reine guerrière face à la colonisation française.',
                'realisateur' => 'Med Hondo',
                'pays' => 'Burkina Faso / Mauritanie',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Étalon de Yennenga 1987',
            ],
            [
                'titre' => 'Buud Yam',
                'duree_min' => 100,
                'annee' => 1997,
                'langue' => 'Mooré',
                'genre' => 'Aventure',
                'synopsis' => 'Suite de Wênd Kûuni, un jeune homme part à la recherche d\'un remède pour sa sœur.',
                'realisateur' => 'Gaston Kaboré',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Étalon de Yennenga 1997',
            ],
            [
                'titre' => 'Dune : Deuxième Partie',
                'titre_original' => 'Dune: Part Two',
                'duree_min' => 166,
                'annee' => 2024,
                'langue' => 'VOSTFR',
                'genre' => 'Science-fiction',
                'synopsis' => 'Paul Atréides s\'unit à Chani et aux Fremen pour se venger des conspirateurs qui ont détruit sa famille.',
                'realisateur' => 'Denis Villeneuve',
                'pays' => 'États-Unis',
                'est_africain' => false,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Inside Out 2',
                'titre_original' => 'Vice-versa 2',
                'duree_min' => 96,
                'annee' => 2024,
                'langue' => 'VF',
                'genre' => 'Animation',
                'synopsis' => 'Riley entre dans l\'adolescence et de nouvelles émotions font leur apparition.',
                'realisateur' => 'Kelsey Mann',
                'pays' => 'États-Unis',
                'est_africain' => false,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Samba Traoré',
                'duree_min' => 85,
                'annee' => 1992,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'Après un braquage, Samba retourne dans son village natal pour y refaire sa vie, mais son passé le rattrape.',
                'realisateur' => 'Idrissa Ouédraogo',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Ours d\'argent - Berlin 1993',
            ],
            [
                'titre' => 'Zan Boko',
                'duree_min' => 100,
                'annee' => 1988,
                'langue' => 'Mooré',
                'genre' => 'Drame',
                'synopsis' => 'Un paysan voit ses terres convoitées par un riche homme d\'affaires, dans un Ouagadougou en pleine expansion.',
                'realisateur' => 'Gaston Kaboré',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Sia, le rêve du python',
                'duree_min' => 95,
                'annee' => 2001,
                'langue' => 'Français',
                'genre' => 'Drame historique',
                'synopsis' => 'Dans un royaume africain mythique, une jeune femme refuse d\'être sacrifiée pour apaiser le python sacré.',
                'realisateur' => 'Dani Kouyaté',
                'pays' => 'Burkina Faso',
                'est_africain' => true,
                'est_burkinabe' => true,
                'prix_fespaco' => 'Étalon de Yennenga 2001',
            ],
            [
                'titre' => 'Moolaadé',
                'duree_min' => 124,
                'annee' => 2004,
                'langue' => 'Wolof',
                'genre' => 'Drame',
                'synopsis' => 'Dans un village malien, une femme accorde sa protection à des fillettes qui refusent l\'excision.',
                'realisateur' => 'Ousmane Sembène',
                'pays' => 'Sénégal',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => 'Un Certain Regard - Cannes 2004',
            ],
            [
                'titre' => 'Xala',
                'duree_min' => 123,
                'annee' => 1975,
                'langue' => 'Wolof',
                'genre' => 'Comédie dramatique',
                'synopsis' => 'Le jour de son troisième mariage, un homme d\'affaires sénégalais est frappé d\'impuissance, satire du pouvoir postcolonial.',
                'realisateur' => 'Ousmane Sembène',
                'pays' => 'Sénégal',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => 'Étalon de Yennenga 1975',
            ],
            [
                'titre' => 'Timbuktu',
                'duree_min' => 97,
                'annee' => 2014,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'Non loin de Tombouctou tombée sous le joug de fondamentalistes, une famille de bergers tente de préserver sa liberté.',
                'realisateur' => 'Abderrahmane Sissako',
                'pays' => 'Mauritanie',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Félicité',
                'duree_min' => 129,
                'annee' => 2017,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'À Kinshasa, une chanteuse se lance dans une course effrénée pour réunir l\'argent d\'une opération pour son fils.',
                'realisateur' => 'Alain Gomis',
                'pays' => 'Sénégal',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => 'Étalon de Yennenga 2017',
            ],
            [
                'titre' => 'La Nuit des rois',
                'duree_min' => 93,
                'annee' => 2020,
                'langue' => 'Français',
                'genre' => 'Drame',
                'synopsis' => 'Dans la prison de la Maca à Abidjan, un nouveau détenu doit raconter une histoire toute une nuit pour survivre.',
                'realisateur' => 'Philippe Lacôte',
                'pays' => 'Côte d\'Ivoire',
                'est_africain' => true,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Oppenheimer',
                'duree_min' => 180,
                'annee' => 2023,
                'langue' => 'VOSTFR',
                'genre' => 'Biopic',
                'synopsis' => 'L\'histoire du physicien J. Robert Oppenheimer et de son rôle dans le développement de la bombe atomique.',
                'realisateur' => 'Christopher Nolan',
                'pays' => 'États-Unis',
                'est_africain' => false,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
            [
                'titre' => 'Vaiana 2',
                'titre_original' => 'Moana 2',
                'duree_min' => 100,
                'annee' => 2024,
                'langue' => 'VF',
                'genre' => 'Animation',
                'synopsis' => 'Vaiana embarque pour un nouveau voyage à travers l\'océan aux côtés de Maui et d\'un nouvel équipage.',
                'realisateur' => 'David Derrick Jr.',
                'pays' => 'États-Unis',
                'est_africain' => false,
                'est_burkinabe' => false,
                'prix_fespaco' => null,
            ],
        ];

        foreach ($films as $data) {
            Film::updateOrCreate(
                ['titre' => $data['titre'], 'annee' => $data['annee']],
                $data
            );
        }
    }
}
